epochs: 5
train_batch_size: 8
validation_batch_size: 8
test_batch_size: 8

train_sample_size: 10000
validation_sample_size: 100
test_sample_size: 1000

learning_rate: 0.00003
weight_decay: 0.01
scheduler_type: 'cosine'
warmup_rate: 0.1

global_attention_mapping: 'none'
log_count: 200

model: 'vanilla_longformer'
model_type: 'longformer'
dataset: 'refined_patents'
labels_list:
  - 'A'
  - 'B'
  - 'C'
  - 'D'
  - 'E'
  - 'F'
  - 'G'
  - 'H'
classes: 12
operation_type: 'train' #'test'
tokenizer: 'longformer_g_section'
log_to_wandb: True
project: 'Long Document Classification'
freeze_layer_count: 0